services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: qwerty
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
    - /Users/prati/Desktop/data:/data/db
    networks:
    - mongo-network

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://qwerty:qwerty@mongo:27017/